apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolet7/flask-app-devsecops.git
    targetRevision: HEAD
    path: flask-app-helm
    helm:
      valueFiles:
        - ../../environments/stage/values-stage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
