apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flask-app
    labels:
      app: flask-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: flask-app
    template:
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "flask-app-dev-role"
          vault.hashicorp.com/agent-inject-secret-env: "secret/data/flask"
          vault.hashicorp.com/agent-inject-template-env: |
            export APP_SECRET_KEY="{{ with secret \"secret/data/flask\" }}{{ .Data.data.APP_SECRET_KEY }}{{ end }}"
            export APP_USERNAME="{{ with secret \"secret/data/flask\" }}{{ .Data.data.APP_USERNAME }}{{ end }}"
            export APP_PASSWORD="{{ with secret \"secret/data/flask\" }}{{ .Data.data.APP_PASSWORD }}{{ end }}"
      labels:
        app: flask-app
      spec:
        serviceAccountName: flask-app
        containers:
        - name: flask-app
          image: {{ .Values.image.repository }}/flask-app:{{ .Values.image.tag | default "latest" }}
          ports:
          - containerPort: 5000
          envFrom:
          - configMapRef:
              name: ignore-if-using-vault  # optional placeholder
