---
name: Epic5_Helm_K8s_Deployment

# Trigger the workflow on pushes and pull requests to main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Linting ensures code quality and style consistency
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flake8
        run: pip install flake8
      - name: Create Flake8 Config
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 120" >> .flake8
          echo "exclude = __init__.py" >> .flake8
      - name: Run lint
        run: |
          if [ -f .flake8 ]; then
            flake8 --config=.flake8 flask-app/*.py
          else
            echo "Flake8 config not found!" && exit 1
          fi

  # Unit tests validate application functionality
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies only
        run: |
          echo "APP_SECRET_KEY=testing-secret" >> $GITHUB_ENV
          echo "APP_USERNAME=admin" >> $GITHUB_ENV
          echo "APP_PASSWORD=adminpass" >> $GITHUB_ENV
          pip install flask pytest python-dotenv
      - name: Run unit tests
        env:
          PYTHONPATH: ./flask-app
        run: pytest flask-app/tests/

  # Static Application Security Testing for code vulnerabilities
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit for SAST
        run: |
          bandit -r flask-app -f json -o bandit-report.json || true
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  # Software Composition Analysis for dependency vulnerabilities
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit for SCA
        run: pip-audit -r flask-app/requirements.txt

  # Build Docker image, scan it, and push to Docker Hub only
  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test, sast, sca]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t flask-app:latest ./flask-app
      - name: Scan image with Trivy (vulnerability scan before upload)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:latest'
          format: 'table'
          exit-code: '0'
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Tag and Push to Docker Hub
        run: |
          docker tag flask-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
      - name: Save image as artifact (for local use or later stages)
        run: docker save flask-app:latest -o flask-app.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-app-image
          path: flask-app.tar

  # Deploy to Dev using Helm
  helm_deploy_dev:
    name: Task 5.1 & 5.2 - Deploy to Dev with Helm
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Deploy to Dev
        run: |
          helm upgrade --install flask-dev ./flask-app-helm \
            --namespace dev --create-namespace \
            -f environments/dev/values-dev.yaml \
            --set ingress.host=192.168.0.189

  # Deploy to Stage using Helm
  helm_deploy_stage:
    name: Task 5.3 - Deploy to Stage with Helm
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Deploy to Stage
        run: |
          helm upgrade --install flask-stage ./flask-app-helm \
            --namespace stage --create-namespace \
            -f environments/stage/values-stage.yaml \
            --set ingress.host=192.168.0.160

